/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PreOrder {
    id: bigint;
    customerName: string;
    status: PreOrderStatus;
    contactInfo: string;
    createdAt: Time;
    orderType: {
        __kind__: "pickup";
        pickup: {
            pickupTime?: string;
        };
    } | {
        __kind__: "delivery";
        delivery: {
            paymentMethod: PaymentMethod;
            specialInstructions?: string;
            address: DeliveryAddress;
            timeSlot: DeliveryTimeSlot;
        };
    };
    items: Array<bigint>;
}
export interface LocationInfo {
    openingHours: string;
    location: string;
}
export interface DeliveryTimeSlot {
    end: string;
    start: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MenuItem {
    id: bigint;
    imagePath?: string;
    name: string;
    createdAt: Time;
    description: string;
    category: MenuCategory;
    price: bigint;
}
export interface GalleryImage {
    id: bigint;
    title: string;
    imagePath: string;
    createdAt: Time;
    description: string;
    category?: MenuCategory;
    isCategoryImage: boolean;
}
export interface SitePublicationStatus {
    publicUrl: string;
    isLive: boolean;
    lastPublishedAt?: Time;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface DeliveryAddress {
    street: string;
    city: string;
    instructions?: string;
    zipCode: string;
}
export interface ContactInfo {
    phoneNumbers: Array<string>;
    email: string;
}
export interface Review {
    id: bigint;
    status: ReviewStatus;
    createdAt: Time;
    reviewerName: string;
    comment: string;
    rating: bigint;
}
export interface UserProfile {
    name: string;
}
export enum MenuCategory {
    bobsMagic = "bobsMagic",
    patiserie = "patiserie",
    inghetataArtizanalaItaliana = "inghetataArtizanalaItaliana",
    waffleStickBombs = "waffleStickBombs",
    snacks = "snacks",
    coffeeMore = "coffeeMore",
    focacciaSpecialitati = "focacciaSpecialitati",
    clatiteWaffles = "clatiteWaffles"
}
export enum PaymentMethod {
    cashOnDelivery = "cashOnDelivery",
    cardOnDelivery = "cardOnDelivery"
}
export enum PreOrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum ReviewStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addDefaultCategoryGalleryImages(): Promise<void>;
    addDefaultClatiteWafflesMenuItems(): Promise<void>;
    addGalleryImage(galleryImage: GalleryImage): Promise<bigint>;
    addMenuItem(menuItem: MenuItem): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    getApprovedReviews(): Promise<Array<Review>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoryGalleryImages(): Promise<Array<GalleryImage>>;
    getContactInfo(): Promise<ContactInfo>;
    getDomainValidationContent(): Promise<string>;
    getFileReference(path: string): Promise<FileReference>;
    getGalleryImages(): Promise<Array<GalleryImage>>;
    getGalleryImagesByCategory(category: MenuCategory): Promise<Array<GalleryImage>>;
    getICPDomainAndValidationToken(): Promise<{
        icpDomain: string;
        validationToken: string;
    }>;
    getLocationInfo(): Promise<LocationInfo>;
    getMenuItems(): Promise<Array<MenuItem>>;
    getMenuItemsByCategory(category: MenuCategory): Promise<Array<MenuItem>>;
    getPreOrder(id: bigint): Promise<PreOrder | null>;
    getPreOrders(): Promise<Array<PreOrder>>;
    getReviews(): Promise<Array<Review>>;
    getSitePublicationStatus(): Promise<SitePublicationStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listFileReferences(): Promise<Array<FileReference>>;
    moderateReview(id: bigint, status: ReviewStatus): Promise<void>;
    placeDeliveryOrder(deliveryOrder: PreOrder): Promise<bigint>;
    placePickupOrder(preOrder: PreOrder): Promise<bigint>;
    publishSite(): Promise<SitePublicationStatus>;
    registerFileReference(path: string, hash: string): Promise<void>;
    removeGalleryImage(id: bigint): Promise<void>;
    removeMenuItem(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setDomainValidationContent(content: string): Promise<void>;
    submitReview(review: Review): Promise<bigint>;
    updateContactInfo(newContactInfo: ContactInfo): Promise<void>;
    updateGalleryImage(id: bigint, galleryImage: GalleryImage): Promise<void>;
    updateLocationInfo(newLocationInfo: LocationInfo): Promise<void>;
    updateMenuItem(id: bigint, menuItem: MenuItem): Promise<void>;
    updatePreOrderStatus(id: bigint, status: PreOrderStatus): Promise<void>;
}
import type { DeliveryAddress as _DeliveryAddress, DeliveryTimeSlot as _DeliveryTimeSlot, GalleryImage as _GalleryImage, MenuCategory as _MenuCategory, MenuItem as _MenuItem, PaymentMethod as _PaymentMethod, PreOrder as _PreOrder, PreOrderStatus as _PreOrderStatus, Review as _Review, ReviewStatus as _ReviewStatus, SitePublicationStatus as _SitePublicationStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addDefaultCategoryGalleryImages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDefaultCategoryGalleryImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDefaultCategoryGalleryImages();
            return result;
        }
    }
    async addDefaultClatiteWafflesMenuItems(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDefaultClatiteWafflesMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDefaultClatiteWafflesMenuItems();
            return result;
        }
    }
    async addGalleryImage(arg0: GalleryImage): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImage(to_candid_GalleryImage_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImage(to_candid_GalleryImage_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMenuItem(arg0: MenuItem): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(to_candid_MenuItem_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(to_candid_MenuItem_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async getApprovedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedReviews();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedReviews();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryGalleryImages();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryGalleryImages();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInfo(): Promise<ContactInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return result;
        }
    }
    async getDomainValidationContent(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDomainValidationContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDomainValidationContent();
            return result;
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImages();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImages();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryImagesByCategory(arg0: MenuCategory): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImagesByCategory(to_candid_MenuCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImagesByCategory(to_candid_MenuCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getICPDomainAndValidationToken(): Promise<{
        icpDomain: string;
        validationToken: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getICPDomainAndValidationToken();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getICPDomainAndValidationToken();
            return result;
        }
    }
    async getLocationInfo(): Promise<LocationInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocationInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocationInfo();
            return result;
        }
    }
    async getMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItemsByCategory(arg0: MenuCategory): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemsByCategory(to_candid_MenuCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemsByCategory(to_candid_MenuCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreOrder(arg0: bigint): Promise<PreOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreOrder(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreOrder(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreOrders(): Promise<Array<PreOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreOrders();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreOrders();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSitePublicationStatus(): Promise<SitePublicationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSitePublicationStatus();
                return from_candid_SitePublicationStatus_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSitePublicationStatus();
            return from_candid_SitePublicationStatus_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async moderateReview(arg0: bigint, arg1: ReviewStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moderateReview(arg0, to_candid_ReviewStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moderateReview(arg0, to_candid_ReviewStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async placeDeliveryOrder(arg0: PreOrder): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeDeliveryOrder(to_candid_PreOrder_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeDeliveryOrder(to_candid_PreOrder_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async placePickupOrder(arg0: PreOrder): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placePickupOrder(to_candid_PreOrder_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placePickupOrder(to_candid_PreOrder_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async publishSite(): Promise<SitePublicationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.publishSite();
                return from_candid_SitePublicationStatus_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishSite();
            return from_candid_SitePublicationStatus_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async removeGalleryImage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGalleryImage(arg0);
            return result;
        }
    }
    async removeMenuItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMenuItem(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setDomainValidationContent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDomainValidationContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDomainValidationContent(arg0);
            return result;
        }
    }
    async submitReview(arg0: Review): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(to_candid_Review_n63(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(to_candid_Review_n63(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateContactInfo(arg0: ContactInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactInfo(arg0);
            return result;
        }
    }
    async updateGalleryImage(arg0: bigint, arg1: GalleryImage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryImage(arg0, to_candid_GalleryImage_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryImage(arg0, to_candid_GalleryImage_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLocationInfo(arg0: LocationInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocationInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocationInfo(arg0);
            return result;
        }
    }
    async updateMenuItem(arg0: bigint, arg1: MenuItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, to_candid_MenuItem_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, to_candid_MenuItem_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePreOrderStatus(arg0: bigint, arg1: PreOrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreOrderStatus(arg0, to_candid_PreOrderStatus_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreOrderStatus(arg0, to_candid_PreOrderStatus_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DeliveryAddress_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryAddress): DeliveryAddress {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_GalleryImage_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryImage): GalleryImage {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_MenuCategory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuCategory): MenuCategory {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_PreOrderStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PreOrderStatus): PreOrderStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_PreOrder_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PreOrder): PreOrder {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewStatus): ReviewStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SitePublicationStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SitePublicationStatus): SitePublicationStatus {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuCategory]): MenuCategory | null {
    return value.length === 0 ? null : from_candid_MenuCategory_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PreOrder]): PreOrder | null {
    return value.length === 0 ? null : from_candid_PreOrder_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ReviewStatus;
    createdAt: _Time;
    reviewerName: string;
    comment: string;
    rating: bigint;
}): {
    id: bigint;
    status: ReviewStatus;
    createdAt: Time;
    reviewerName: string;
    comment: string;
    rating: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ReviewStatus_n19(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        reviewerName: value.reviewerName,
        comment: value.comment,
        rating: value.rating
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    imagePath: string;
    createdAt: _Time;
    description: string;
    category: [] | [_MenuCategory];
    isCategoryImage: boolean;
}): {
    id: bigint;
    title: string;
    imagePath: string;
    createdAt: Time;
    description: string;
    category?: MenuCategory;
    isCategoryImage: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        imagePath: value.imagePath,
        createdAt: value.createdAt,
        description: value.description,
        category: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.category)),
        isCategoryImage: value.isCategoryImage
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    imagePath: [] | [string];
    name: string;
    createdAt: _Time;
    description: string;
    category: _MenuCategory;
    price: bigint;
}): {
    id: bigint;
    imagePath?: string;
    name: string;
    createdAt: Time;
    description: string;
    category: MenuCategory;
    price: bigint;
} {
    return {
        id: value.id,
        imagePath: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.imagePath)),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        category: from_candid_MenuCategory_n28(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _PreOrderStatus;
    contactInfo: string;
    createdAt: _Time;
    orderType: {
        pickup: {
            pickupTime: [] | [string];
        };
    } | {
        delivery: {
            paymentMethod: _PaymentMethod;
            specialInstructions: [] | [string];
            address: _DeliveryAddress;
            timeSlot: _DeliveryTimeSlot;
        };
    };
    items: Array<bigint>;
}): {
    id: bigint;
    customerName: string;
    status: PreOrderStatus;
    contactInfo: string;
    createdAt: Time;
    orderType: {
        __kind__: "pickup";
        pickup: {
            pickupTime?: string;
        };
    } | {
        __kind__: "delivery";
        delivery: {
            paymentMethod: PaymentMethod;
            specialInstructions?: string;
            address: DeliveryAddress;
            timeSlot: DeliveryTimeSlot;
        };
    };
    items: Array<bigint>;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_PreOrderStatus_n37(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        createdAt: value.createdAt,
        orderType: from_candid_variant_n39(_uploadFile, _downloadFile, value.orderType),
        items: value.items
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pickupTime: [] | [string];
}): {
    pickupTime?: string;
} {
    return {
        pickupTime: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.pickupTime))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: _PaymentMethod;
    specialInstructions: [] | [string];
    address: _DeliveryAddress;
    timeSlot: _DeliveryTimeSlot;
}): {
    paymentMethod: PaymentMethod;
    specialInstructions?: string;
    address: DeliveryAddress;
    timeSlot: DeliveryTimeSlot;
} {
    return {
        paymentMethod: from_candid_PaymentMethod_n42(_uploadFile, _downloadFile, value.paymentMethod),
        specialInstructions: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.specialInstructions)),
        address: from_candid_DeliveryAddress_n44(_uploadFile, _downloadFile, value.address),
        timeSlot: value.timeSlot
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    street: string;
    city: string;
    instructions: [] | [string];
    zipCode: string;
}): {
    street: string;
    city: string;
    instructions?: string;
    zipCode: string;
} {
    return {
        street: value.street,
        city: value.city,
        instructions: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.instructions)),
        zipCode: value.zipCode
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    publicUrl: string;
    isLive: boolean;
    lastPublishedAt: [] | [_Time];
}): {
    publicUrl: string;
    isLive: boolean;
    lastPublishedAt?: Time;
} {
    return {
        publicUrl: value.publicUrl,
        isLive: value.isLive,
        lastPublishedAt: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.lastPublishedAt))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ReviewStatus {
    return "pending" in value ? ReviewStatus.pending : "approved" in value ? ReviewStatus.approved : "rejected" in value ? ReviewStatus.rejected : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bobsMagic: null;
} | {
    patiserie: null;
} | {
    inghetataArtizanalaItaliana: null;
} | {
    waffleStickBombs: null;
} | {
    snacks: null;
} | {
    coffeeMore: null;
} | {
    focacciaSpecialitati: null;
} | {
    clatiteWaffles: null;
}): MenuCategory {
    return "bobsMagic" in value ? MenuCategory.bobsMagic : "patiserie" in value ? MenuCategory.patiserie : "inghetataArtizanalaItaliana" in value ? MenuCategory.inghetataArtizanalaItaliana : "waffleStickBombs" in value ? MenuCategory.waffleStickBombs : "snacks" in value ? MenuCategory.snacks : "coffeeMore" in value ? MenuCategory.coffeeMore : "focacciaSpecialitati" in value ? MenuCategory.focacciaSpecialitati : "clatiteWaffles" in value ? MenuCategory.clatiteWaffles : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): PreOrderStatus {
    return "cancelled" in value ? PreOrderStatus.cancelled : "pending" in value ? PreOrderStatus.pending : "completed" in value ? PreOrderStatus.completed : "confirmed" in value ? PreOrderStatus.confirmed : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pickup: {
        pickupTime: [] | [string];
    };
} | {
    delivery: {
        paymentMethod: _PaymentMethod;
        specialInstructions: [] | [string];
        address: _DeliveryAddress;
        timeSlot: _DeliveryTimeSlot;
    };
}): {
    __kind__: "pickup";
    pickup: {
        pickupTime?: string;
    };
} | {
    __kind__: "delivery";
    delivery: {
        paymentMethod: PaymentMethod;
        specialInstructions?: string;
        address: DeliveryAddress;
        timeSlot: DeliveryTimeSlot;
    };
} {
    return "pickup" in value ? {
        __kind__: "pickup",
        pickup: from_candid_record_n40(_uploadFile, _downloadFile, value.pickup)
    } : "delivery" in value ? {
        __kind__: "delivery",
        delivery: from_candid_record_n41(_uploadFile, _downloadFile, value.delivery)
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cashOnDelivery: null;
} | {
    cardOnDelivery: null;
}): PaymentMethod {
    return "cashOnDelivery" in value ? PaymentMethod.cashOnDelivery : "cardOnDelivery" in value ? PaymentMethod.cardOnDelivery : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryImage>): Array<GalleryImage> {
    return value.map((x)=>from_candid_GalleryImage_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PreOrder>): Array<PreOrder> {
    return value.map((x)=>from_candid_PreOrder_n35(_uploadFile, _downloadFile, x));
}
function to_candid_DeliveryAddress_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryAddress): _DeliveryAddress {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_GalleryImage_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryImage): _GalleryImage {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_MenuCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): _MenuCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_MenuItem_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItem): _MenuItem {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_PreOrderStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PreOrderStatus): _PreOrderStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_PreOrder_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PreOrder): _PreOrder {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_ReviewStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): _ReviewStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_Review_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Review): _Review {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    imagePath?: string;
    name: string;
    createdAt: Time;
    description: string;
    category: MenuCategory;
    price: bigint;
}): {
    id: bigint;
    imagePath: [] | [string];
    name: string;
    createdAt: _Time;
    description: string;
    category: _MenuCategory;
    price: bigint;
} {
    return {
        id: value.id,
        imagePath: value.imagePath ? candid_some(value.imagePath) : candid_none(),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        category: to_candid_MenuCategory_n10(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: PreOrderStatus;
    contactInfo: string;
    createdAt: Time;
    orderType: {
        __kind__: "pickup";
        pickup: {
            pickupTime?: string;
        };
    } | {
        __kind__: "delivery";
        delivery: {
            paymentMethod: PaymentMethod;
            specialInstructions?: string;
            address: DeliveryAddress;
            timeSlot: DeliveryTimeSlot;
        };
    };
    items: Array<bigint>;
}): {
    id: bigint;
    customerName: string;
    status: _PreOrderStatus;
    contactInfo: string;
    createdAt: _Time;
    orderType: {
        pickup: {
            pickupTime: [] | [string];
        };
    } | {
        delivery: {
            paymentMethod: _PaymentMethod;
            specialInstructions: [] | [string];
            address: _DeliveryAddress;
            timeSlot: _DeliveryTimeSlot;
        };
    };
    items: Array<bigint>;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: to_candid_PreOrderStatus_n54(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        createdAt: value.createdAt,
        orderType: to_candid_variant_n56(_uploadFile, _downloadFile, value.orderType),
        items: value.items
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    specialInstructions?: string;
    address: DeliveryAddress;
    timeSlot: DeliveryTimeSlot;
}): {
    paymentMethod: _PaymentMethod;
    specialInstructions: [] | [string];
    address: _DeliveryAddress;
    timeSlot: _DeliveryTimeSlot;
} {
    return {
        paymentMethod: to_candid_PaymentMethod_n58(_uploadFile, _downloadFile, value.paymentMethod),
        specialInstructions: value.specialInstructions ? candid_some(value.specialInstructions) : candid_none(),
        address: to_candid_DeliveryAddress_n60(_uploadFile, _downloadFile, value.address),
        timeSlot: value.timeSlot
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    street: string;
    city: string;
    instructions?: string;
    zipCode: string;
}): {
    street: string;
    city: string;
    instructions: [] | [string];
    zipCode: string;
} {
    return {
        street: value.street,
        city: value.city,
        instructions: value.instructions ? candid_some(value.instructions) : candid_none(),
        zipCode: value.zipCode
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pickupTime?: string;
}): {
    pickupTime: [] | [string];
} {
    return {
        pickupTime: value.pickupTime ? candid_some(value.pickupTime) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: ReviewStatus;
    createdAt: Time;
    reviewerName: string;
    comment: string;
    rating: bigint;
}): {
    id: bigint;
    status: _ReviewStatus;
    createdAt: _Time;
    reviewerName: string;
    comment: string;
    rating: bigint;
} {
    return {
        id: value.id,
        status: to_candid_ReviewStatus_n50(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        reviewerName: value.reviewerName,
        comment: value.comment,
        rating: value.rating
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    imagePath: string;
    createdAt: Time;
    description: string;
    category?: MenuCategory;
    isCategoryImage: boolean;
}): {
    id: bigint;
    title: string;
    imagePath: string;
    createdAt: _Time;
    description: string;
    category: [] | [_MenuCategory];
    isCategoryImage: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        imagePath: value.imagePath,
        createdAt: value.createdAt,
        description: value.description,
        category: value.category ? candid_some(to_candid_MenuCategory_n10(_uploadFile, _downloadFile, value.category)) : candid_none(),
        isCategoryImage: value.isCategoryImage
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): {
    bobsMagic: null;
} | {
    patiserie: null;
} | {
    inghetataArtizanalaItaliana: null;
} | {
    waffleStickBombs: null;
} | {
    snacks: null;
} | {
    coffeeMore: null;
} | {
    focacciaSpecialitati: null;
} | {
    clatiteWaffles: null;
} {
    return value == MenuCategory.bobsMagic ? {
        bobsMagic: null
    } : value == MenuCategory.patiserie ? {
        patiserie: null
    } : value == MenuCategory.inghetataArtizanalaItaliana ? {
        inghetataArtizanalaItaliana: null
    } : value == MenuCategory.waffleStickBombs ? {
        waffleStickBombs: null
    } : value == MenuCategory.snacks ? {
        snacks: null
    } : value == MenuCategory.coffeeMore ? {
        coffeeMore: null
    } : value == MenuCategory.focacciaSpecialitati ? {
        focacciaSpecialitati: null
    } : value == MenuCategory.clatiteWaffles ? {
        clatiteWaffles: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ReviewStatus.pending ? {
        pending: null
    } : value == ReviewStatus.approved ? {
        approved: null
    } : value == ReviewStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PreOrderStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == PreOrderStatus.cancelled ? {
        cancelled: null
    } : value == PreOrderStatus.pending ? {
        pending: null
    } : value == PreOrderStatus.completed ? {
        completed: null
    } : value == PreOrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "pickup";
    pickup: {
        pickupTime?: string;
    };
} | {
    __kind__: "delivery";
    delivery: {
        paymentMethod: PaymentMethod;
        specialInstructions?: string;
        address: DeliveryAddress;
        timeSlot: DeliveryTimeSlot;
    };
}): {
    pickup: {
        pickupTime: [] | [string];
    };
} | {
    delivery: {
        paymentMethod: _PaymentMethod;
        specialInstructions: [] | [string];
        address: _DeliveryAddress;
        timeSlot: _DeliveryTimeSlot;
    };
} {
    return value.__kind__ === "pickup" ? {
        pickup: to_candid_record_n62(_uploadFile, _downloadFile, value.pickup)
    } : value.__kind__ === "delivery" ? {
        delivery: to_candid_record_n57(_uploadFile, _downloadFile, value.delivery)
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cashOnDelivery: null;
} | {
    cardOnDelivery: null;
} {
    return value == PaymentMethod.cashOnDelivery ? {
        cashOnDelivery: null
    } : value == PaymentMethod.cardOnDelivery ? {
        cardOnDelivery: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
